
services:
  ubuntu1:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      shared_network:
        ipv4_address: 172.20.0.2  # Fixed IP for ubuntu1
    volumes:
      - "/Users/karan/Documents/Uni Work/CSC409:/shared"
    container_name: ubuntu_container_1
    restart: "unless-stopped"

  ubuntu2:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      shared_network:
        ipv4_address: 172.20.0.3  # Fixed IP for ubuntu2
    volumes:
      - "/Users/karan/Documents/Uni Work/CSC409:/shared"
    container_name: ubuntu_container_2
    restart: "unless-stopped"

  ubuntu3:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      shared_network:
        ipv4_address: 172.20.0.4  # Fixed IP for ubuntu3
    volumes:
      - "/Users/karan/Documents/Uni Work/CSC409:/shared"
    container_name: ubuntu_container_3
    restart: "unless-stopped"

  ubuntu4:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      shared_network:
        ipv4_address: 172.20.0.5  # Fixed IP for ubuntu4
    volumes:
      - "/Users/karan/Documents/Uni Work/CSC409:/shared"
    container_name: ubuntu_container_4
    restart: "unless-stopped"

networks:
  shared_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16  # Custom subnet for the network
